### ISSUE TITLE
Add support for TTC directions

### ISSUE THREAD

**Issue by Swithord** [nsaroiu/TTC-Tracker#23]
Technical plan:
- Add direction parameter in Route
- Add direction tag parameter in Vehicle (& change the current direction parameter name to heading or something)
- Update DAO to get direction and instantiate Route and Vehicles correctly
- Add stop name to StopData.csv
- Add stop name parameter in Stop (and update Stop DAO accordingly)

**Comment by nsaroiu** [comment]
- Add Stop name to StopData.csv
