### ISSUE TITLE
Update Display Stops Use Case to return name of Stops

### ISSUE THREAD

**Issue by nsaroiu** [nsaroiu/TTC-Tracker#41]
In addition to returning a list of stop tags and their respective locations, the Display Stops use case should also return each stop's respective name. When a user clicks on a stop icon on the map, we should show the stop's name before the user "expands" into the stop (and would therefore need stop details). This offers the user the chance to know the stop's name before having the backend return the specific details of the stop.

Alternatively, it might just be better for the Display Stops use case to return a list of all stops (basically just call stopDAO.getAllStops() and call it a day). Because we store all stop data in a csv file and the use case already has to iterate through the whole csv file, it's not significantly slower to just return all the data in the csv file.

**Comment by nsaroiu** [comment]
@prash-red I've added you as the assignee for this use case since you are dealing with the frontend and therefore should have the best idea on implementing this.

**Comment by prash-red** [comment]
Aight. I'll start working on this. 👍
![KanyeEastGIF](https://github.com/nsaroiu/TTC-Tracker/assets/111243248/41591aec-a565-4283-8cf3-af0270275dac)
