### ISSUE TITLE
Testing for Predictions use-case

### ISSUE THREAD

**Issue by prash-red** [nsaroiu/TTC-Tracker#70]
### Problem Statement
Testing for the Predictions use-case needs to be established to ensure the reliability and correctness of the implemented features.

### Scope
This issue covers the creation and execution of test cases for the Predictions use-case.

### Tasks
1. **Unit Testing**: Implement unit tests for individual components of the Predictions use-case, such as controllers, strategies, and data processing functions.

2. **Scenario-based Testing**: Create test scenarios that mimic real-world user interactions with the Stop-Details feature. Include cases with different input variations and expected outcomes.

3. **Edge Case Testing**: Identify and test edge cases to validate the behavior of the Stop-Details use-case under extreme or unexpected conditions.

### Acceptance Criteria
- All unit tests pass successfully, ensuring the correctness of individual components.
- The test suite includes comprehensive coverage of various scenarios.

**Comment by nsaroiu** [comment]
Solved
